apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/urcomputeringpal-public/nuc-node-led-controller
deploy:
  kubectl:
    manifests:
    - config/kubernetes/default/**/*.yaml
