apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nuc-node-led-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nuc-node-led-controller
subjects:
- kind: ServiceAccount
  name: nuc-node-led-controller
  namespace: default
